#!/usr/bin/env python
# -*- coding:utf-8 -*-

a_list = [5,7,1,3]

for i in xrange(len(a_list)-1):
	for j in xrange(len(a_list)-1-i):
		if a_list[j] >a_list[j+1]:
			a_list[j],a_list[j+1] = a_list[j+1],a_list[j]

print a_list
